# Generated by Django 2.2.7 on 2020-01-27 11:42

import authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('dob', models.DateField(blank=True, null=True)),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('books_in_collection', models.IntegerField(blank=True, default=0, null=True, verbose_name='Books in Collection')),
                ('image', models.ImageField(blank=True, null=True, upload_to=authors.models.upload_photo, verbose_name='Photo')),
            ],
        ),
    ]
