# Generated by Django 2.2.7 on 2020-01-27 11:42

import books.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Book Title')),
                ('book_src', models.FileField(blank=True, null=True, upload_to=books.models.upload_book, verbose_name='Book Source')),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('published_on', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('genre', models.CharField(choices=[('adventure', 'Adventure'), ('history', 'History'), ('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction')], max_length=50)),
                ('photo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='Book_Covers/')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Stars')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Your Comment')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_review', to='books.Book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
